### PR TITLE
Major release as its breaking backward compatibility

### PR DESCRIPTION
**Pull request by tatvarth**

### CODE REVIEW

**Comment by xjamundx** [comment]
I already published this as 1.4.0, but....why do you consider this breaking. It shouldn't be right?

**Comment by tatvarth** [comment]
What if someone using this package wants to stick to es5. I would assume it will break because Object.assign will cause problems. Please correct me if I misunderstood. Also, for donating this code to krakenjs, I spoke to Mark Stuart, if you make him an owner of neff, then he’ll transfer it to github.com/krakenjs

**Comment by mstuart** [comment]
Looks like Object.assign has been supported since node@4.  I'd be okay rollin' w/ it without a major version, but if you feel strongly about it, I'd be up for major versioning it.  lmk.

**Comment by tatvarth** [comment]
We should be good then! Thanks @xjamundx  @mstuart

**Pull request closed without merging**
